// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHLms5gFTepmseWm-wYKxVO0IMMOhzQA',
    appId: '1:702324940608:web:6bfdb308725f5d38e564a5',
    messagingSenderId: '702324940608',
    projectId: 'on-spot-mechanic-3f5ac',
    authDomain: 'on-spot-mechanic-3f5ac.firebaseapp.com',
    storageBucket: 'on-spot-mechanic-3f5ac.appspot.com',
    measurementId: 'G-MMYDV2BBNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYb_N7i_d5U5FCZoChbz-pd1RWf-Dx6Ps',
    appId: '1:702324940608:android:703e8a21aaa06ef7e564a5',
    messagingSenderId: '702324940608',
    projectId: 'on-spot-mechanic-3f5ac',
    storageBucket: 'on-spot-mechanic-3f5ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAosAbYaPIxEAnPa2P8xZ8TWOh5j3degKE',
    appId: '1:702324940608:ios:b1c9992ef7ae134ce564a5',
    messagingSenderId: '702324940608',
    projectId: 'on-spot-mechanic-3f5ac',
    storageBucket: 'on-spot-mechanic-3f5ac.appspot.com',
    iosBundleId: 'com.example.onSpotMechanic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAosAbYaPIxEAnPa2P8xZ8TWOh5j3degKE',
    appId: '1:702324940608:ios:d1b5f90513b0f2d1e564a5',
    messagingSenderId: '702324940608',
    projectId: 'on-spot-mechanic-3f5ac',
    storageBucket: 'on-spot-mechanic-3f5ac.appspot.com',
    iosBundleId: 'com.example.onSpotMechanic.RunnerTests',
  );
}
